version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
  db:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE_URL=carparts_db
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - carparts_db:/var/lib/postgresql/data

volumes:
  carparts_db:
    driver: local
